### PR TITLE
Use MatrixGenerics

### PR DESCRIPTION
**Pull request by const-ae**
Hi Pete, 

I created a first draft how `DelayedMatrixStats` could use the functions from the `MatrixGenerics` package.

Best, Constantin

### CODE REVIEW

**Comment by const-ae** [comment]
I am not sure what is the best way to handle the remaining functions `colMins`, `colMaxs`, and `colRanges` which are implemented in https://github.com/Bioconductor/DelayedArray.

**Comment by PeteHaitch** [comment]
Thanks @const-ae, I really appreciate this!
Just a note that I won't be able to merge the PR until **MatrixGenerics** is available on CRAN or Bioconductor since Bioconductor packages can only depend on packages available through there.
But I will try to take a closer look at it over the Christmas break and I'll keep an eye on **MatrixGenerics** development.

**Comment by const-ae** [comment]
Thanks, no problem. I anyway thought of this PR more as a proof of principle than something that would be merged immediately.

My question is, do you agree that the current structure of the `MatrixGenerics` functions is the way to go forward? Otherwise, I think there is little point in implementing more methods.

**Comment by const-ae** [comment]
Hey Pete,
any updates from your side?
Best, Constantin

**Comment by PeteHaitch** [comment]
Sorry for the silence, Constantin.
I've been swamped with non-BioC work and will be for the remainder of the month.
So I won't be returning to this until March, but would this would hopefully give us enough time to target the next BioC release (pending **MatrixGenerics** being available from CRAN/BioC)

**Comment by const-ae** [comment]
Hi Pete,

thanks for your response. I am glad that you agree that it would be great to target the next BioConductor release :)

I can take care of submitting **MatrixGenerics**, I would however need either commit rights to the https://github.com/Bioconductor/MatrixGenerics repo or would go ahead and submit my fork https://github.com/const-ae/MatrixGenerics.

**Comment by PeteHaitch** [comment]
You should now have write access

**Comment by const-ae** [comment]
Nice, thank you very much :)

**Comment by PeteHaitch** [comment]
Closing in favour of https://github.com/PeteHaitch/DelayedMatrixStats/pull/62

**Pull request closed without merging**
