### PR TITLE
Use BLOCK_colVars/BLOCK_rowVars workhorses for colVars/rowVars methods

### PR DESCRIPTION
**Pull request by PeteHaitch**
- Reimplements https://github.com/PeteHaitch/DelayedMatrixStats/pull/94 on top of current version

### CODE REVIEW

**Comment by PeteHaitch** [comment]
@hpages this tickled an edge case in the unit tests **DelayedMatrixStats**.
Simplified example below:

``` r
suppressPackageStartupMessages(library(DelayedArray))
suppressPackageStartupMessages(library(HDF5Array))

# Works
x <- DelayedArray(matrix(0L, nrow = 0, ncol = 0))
DelayedArray:::BLOCK_colVars(x)
#> numeric(0)

# Errors
X <- as(x, "HDF5Array")
DelayedArray:::BLOCK_colVars(X)
#> Warning in best_grid_for_vstrip_apply(x, grid = grid): NAs introduced by
#> coercion to integer range
#> Error in colAutoGrid(x, ncol = block_ncol): 'ncol' must be a single integer or NULL
```

<sup>Created on 2023-07-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16)
#>  os       Ubuntu 22.04.2 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language en_AU:en
#>  collate  en_AU.UTF-8
#>  ctype    en_AU.UTF-8
#>  tz       Australia/Melbourne
#>  date     2023-07-25
#>  pandoc   3.1.1 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  ! package        * version date (UTC) lib source
#>    BiocGenerics   * 0.47.0  2023-04-25 [1] Bioconductor
#>  P cli              3.6.1   2023-03-23 [?] RSPM (R 4.3.0)
#>  P crayon           1.5.2   2022-09-29 [?] RSPM (R 4.3.0)
#>    DelayedArray   * 0.27.9  2023-07-04 [1] Bioconductor
#>  P digest           0.6.33  2023-07-07 [?] RSPM (R 4.3.0)
#>  P evaluate         0.21    2023-05-05 [?] RSPM (R 4.3.0)
#>  P fastmap          1.1.1   2023-02-24 [?] RSPM (R 4.2.0)
#>  P fs               1.6.3   2023-07-20 [?] RSPM (R 4.3.0)
#>  P glue             1.6.2   2022-02-24 [?] RSPM (R 4.3.0)
#>    HDF5Array      * 1.29.3  2023-05-05 [1] Bioconductor
#>  P htmltools        0.5.5   2023-03-23 [?] RSPM (R 4.2.0)
#>    IRanges        * 2.35.2  2023-06-22 [1] Bioconductor
#>  P knitr            1.43    2023-05-25 [?] RSPM (R 4.2.0)
#>  P lattice          0.21-8  2023-04-05 [?] RSPM (R 4.3.0)
#>  P lifecycle        1.0.3   2022-10-07 [?] RSPM (R 4.3.0)
#>  P Matrix         * 1.6-0   2023-07-08 [?] RSPM (R 4.3.0)
#>  P MatrixGenerics * 1.13.1  2023-07-24 [?] Github (Bioconductor/MatrixGenerics@09cb5cb)
#>  P matrixStats    * 1.0.0   2023-06-02 [?] RSPM (R 4.3.0)
#>  P reprex           2.0.2   2022-08-17 [?] RSPM (R 4.3.0)
#>    rhdf5          * 2.45.1  2023-07-10 [1] Bioconductor
#>    rhdf5filters     1.13.5  2023-07-19 [1] Bioconductor
#>    Rhdf5lib         1.23.0  2023-04-25 [1] Bioconductor
#>  P rlang            1.1.1   2023-04-28 [?] RSPM (R 4.3.0)
#>  P rmarkdown        2.23    2023-07-01 [?] RSPM (R 4.2.0)
#>  P rstudioapi       0.15.0  2023-07-07 [?] RSPM (R 4.2.0)
#>    S4Arrays       * 1.1.4   2023-05-14 [1] Bioconductor
#>    S4Vectors      * 0.39.1  2023-05-03 [1] Bioconductor
#>  P sessioninfo      1.2.2   2021-12-06 [?] RSPM (R 4.2.0)
#>    SparseArray    * 1.1.10  2023-06-11 [1] Bioconductor
#>  P withr            2.5.0   2022-03-03 [?] RSPM (R 4.3.0)
#>  P xfun             0.39    2023-04-20 [?] RSPM (R 4.2.0)
#>    XVector          0.41.1  2023-05-03 [1] Bioconductor
#>  P yaml             2.3.7   2023-01-23 [?] RSPM (R 4.2.0)
#>    zlibbioc         1.47.0  2023-04-25 [1] Bioconductor
#> 
#>  [1] /home/peter/.cache/R/renv/library/DelayedMatrixStats-a72d0e47/R-4.3/x86_64-pc-linux-gnu
#>  [2] /home/peter/.cache/R/renv/sandbox/R-4.3/x86_64-pc-linux-gnu/9a444a72
#>  [3] /usr/lib/R/library
#> 
#>  P ── Loaded and on-disk path mismatch.
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by hpages** [comment]
Ah ok, that's a good catch. Let me fix this in **DelayedArray**. I don't think you actually need to do anything in **DelayedMatrixStats**. I'll let you know.

**Comment by hpages** [comment]
Fixed in **DelayedArray** 0.27.10. See https://github.com/Bioconductor/DelayedArray/commit/5544cc3e06d66c209c5394f675805d7ab6890f03

**Comment by PeteHaitch** [comment]
Thanks!

**Pull request merged**
